# Gradle settings
org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin settings
kotlin.code.style=official
kotlin.incremental=true

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true
