---
# Domain
domain: tv.adapto.kz
letsencrypt_email: admin@adapto.kz

# App
app_name: playoutedge
app_dir: /opt/playoutedge
app_port: 8080

# Database
db_name: playoutedge
db_user: playoutedge
db_password: "{{ vault_db_password | default('YDj16bvWxxX3K1nn4gRxY4VgZmbOl9td') }}"

# JWT
jwt_secret: "{{ vault_jwt_secret | default('YsrSD1JvLaRjA73E1YjK9RlvWKPTqlUWdRVkNtuLEOhfPtRIJZOpX6pDTjawbWvA') }}"

# SSH
ssh_port: 22
deploy_user: deploy
